language: node_js
node_js:
- '0.10'
cache:
  bundler: true
  directories:
  - node_modules
env: NODE_ENV=test
deploy:
  provider: opsworks
  access_key_id: AKIAIT4X4NDGM2WVL6VA
  secret-access-key:
    secure: ILcjgHa8m/HA4B/O5twwoBe2Cvz2JvAfTUsFY76X7cQKQ3LMT0L1gesO9Bp2iwPLBlFK0+1OrjsCVxdbo483qTo/SCHOREoYC9S5s5iNIbPzOWQkLy2pjJlQJAHD7JUasz7WGniaWAg1YFK0ujJV2NpJ7QmZ2V6bdgwumUuiEgk=
  app-id: a3f07af5-99e9-4c17-854c-50aef9c540dd
  on:
    branch: staging
branches:
  only:
  - master
  - staging
